[masters]
master-node ansible_host={{ lookup('env', 'MASTER_IP') }} ansible_user={{ lookup('env', 'ANSIBLE_USER') | default('ubuntu') }} ansible_ssh_pass={{ lookup('env', 'MASTER_PASSWORD') | default(lookup('env', 'VM_PASSWORD')) }} ansible_become_pass={{ lookup('env', 'MASTER_PASSWORD') | default(lookup('env', 'VM_PASSWORD')) }}

[workers]
worker-1 ansible_host={{ lookup('env', 'WORKER1_IP') }} ansible_user={{ lookup('env', 'ANSIBLE_USER') | default('ubuntu') }} ansible_ssh_pass={{ lookup('env', 'WORKER1_PASSWORD') | default(lookup('env', 'VM_PASSWORD')) }} ansible_become_pass={{ lookup('env', 'WORKER1_PASSWORD') | default(lookup('env', 'VM_PASSWORD')) }}
worker-2 ansible_host={{ lookup('env', 'WORKER2_IP') }} ansible_user={{ lookup('env', 'ANSIBLE_USER') | default('ubuntu') }} ansible_ssh_pass={{ lookup('env', 'WORKER2_PASSWORD') | default(lookup('env', 'VM_PASSWORD')) }} ansible_become_pass={{ lookup('env', 'WORKER2_PASSWORD') | default(lookup('env', 'VM_PASSWORD')) }}

[k8s_cluster:children]
masters
workers

[k8s_cluster:vars]
# Common variables
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_host_key_checking=false
kubernetes_version={{ lookup('env', 'KUBERNETES_VERSION') | default('1.28.2') }}
container_runtime=containerd
pod_network_cidr={{ lookup('env', 'POD_NETWORK_CIDR') | default('10.244.0.0/16') }}
service_cidr={{ lookup('env', 'SERVICE_CIDR') | default('10.96.0.0/12') }}

# Docker registry credentials
docker_registry_url=docker.io
docker_registry_username={{ lookup('env', 'DOCKER_USERNAME') | default('YOUR_DOCKER_USERNAME') }}
docker_registry_password={{ lookup('env', 'DOCKER_PASSWORD') | default('YOUR_DOCKER_PASSWORD') }}
