---
# Install Prometheus for monitoring
- name: Create monitoring namespace
  shell: kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install Prometheus with Helm
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update
    helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --set prometheus.service.type=NodePort --set prometheus.service.nodePort=30090 --set grafana.service.type=NodePort --set grafana.service.nodePort=30091
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Wait for Prometheus to be ready
  shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=prometheus -n monitoring --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
