---
# Common setup for all nodes
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - ufw
    state: present

- name: Disable swap permanently
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Make br_netfilter persistent
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: br_netfilter
    create: yes

- name: Configure sysctl for Kubernetes
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward

- name: Configure UFW to allow Kubernetes ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "6443" # Kubernetes API
    - "2379:2380" # etcd
    - "10250" # kubelet
    - "10251" # kube-scheduler
    - "10252" # kube-controller-manager
    - "30000:32767" # NodePort services

- name: Enable UFW
  ufw:
    state: enabled
    policy: allow
