---
- name: Initialize Kubernetes master node
  hosts: master
  become: yes
  gather_facts: yes
  vars:
    pod_cidr: "10.244.0.0/16"
    service_cidr: "10.96.0.0/12"
    
  tasks:
    - name: Check if kubeadm has already run
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeadm_already_run
      
    - name: Initialize Kubernetes cluster
      shell: |
        kubeadm init \
          --pod-network-cidr={{ pod_cidr }} \
          --service-cidr={{ service_cidr }} \
          --apiserver-advertise-address={{ ansible_default_ipv4.address }}
      when: not kubeadm_already_run.stat.exists
      register: kubeadm_init_result
      
    - name: Create .kube directory for root
      file:
        path: /root/.kube
        state: directory
        mode: '0755'
        
    - name: Copy admin.conf to root's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: '0644'
        
    - name: Install Flannel CNI
      shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      when: not kubeadm_already_run.stat.exists
      
    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: join_command_result
      
    - name: Save join command to file
      copy:
        content: "{{ join_command_result.stdout }}"
        dest: /tmp/join-command
        
    - name: Fetch join command to local machine
      fetch:
        src: /tmp/join-command
        dest: /tmp/join-command
        flat: yes
