---
# Install Traefik Ingress Controller
- name: Create Traefik namespace
  shell: kubectl create namespace traefik --dry-run=client -o yaml | kubectl apply -f -
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install Traefik with Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    helm repo add traefik https://traefik.github.io/charts
    helm repo update
    helm install traefik traefik/traefik --namespace traefik --set service.type=NodePort --set ports.web.nodePort=30080 --set ports.websecure.nodePort=30443
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Wait for Traefik to be ready
  shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=traefik -n traefik --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
